const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('cadastro: privilégios, aprovação, confirmação e isolamento no PostgreSQL',async()=>{
 const db=new PGlite();
 try {
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public to anon,authenticated;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb,email_confirmed_at timestamptz);
 create table profiles(id uuid primary key,name text,email text,role text,active boolean default true,plan_type text default 'basic',first_access boolean default false);
 create table students(id uuid primary key,professor_id uuid,user_id uuid);
 alter table profiles enable row level security;
 create policy profiles_update on profiles for update using(id=auth.uid()) with check(id=auth.uid());
 create policy profiles_insert on profiles for insert with check(id=auth.uid());
 create policy profiles_select on profiles for select using(id=auth.uid());
 grant all on profiles,students to anon,authenticated;
 insert into profiles(id,role) values('${id(1)}','admin'),('${id(2)}','professor');
 `);
 for(const t of ['plans','plan_days','plan_exercises','exercises','scheduled_assessments','assessments']) await db.exec(`create table ${t}(id uuid); grant all on ${t} to anon,authenticated; create policy legacy on ${t} for all using(true) with check(true);`);
 const sql=fs.readFileSync('backend/cadastro-professor.sql','utf8');
 await db.exec(sql); await db.exec(sql);
 await db.exec('create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user()');
 await db.query('insert into auth.users values($1,$2,$3,null)',[id(3),'test@example.com',JSON.stringify({role:'admin',name:'Teste'})]);
 assert.deepEqual((await db.query('select role,approval_status from profiles where id=$1',[id(3)])).rows[0],{role:'professor',approval_status:'pending'});
 assert.equal((await db.query('select approval_status from profiles where id=$1',[id(2)])).rows[0].approval_status,'approved');
 const login=async n=>db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${id(n)}';`);
 await login(3);
 await assert.rejects(db.exec("update profiles set role='admin'"),/protegidos/);
 await assert.rejects(db.exec("update profiles set approval_status='approved'"),/protegidos/);
 await assert.rejects(db.exec("update profiles set plan_type='unlimited'"),/protegidos/);
 await db.exec("update profiles set name='Novo nome'");
 await assert.rejects(db.query('insert into students values($1,$2,null)',[id(10),id(3)]));
 await assert.rejects(db.exec('insert into exercises values(null)'));
 await assert.rejects(db.query("select review_professor($1,'approved','basic')",[id(3)]),/administrador/);
 await login(1);
 await assert.rejects(db.query("select review_professor($1,'approved','basic')",[id(3)]),/confirmar/);
 await db.exec('reset role');
 await db.query('update auth.users set email_confirmed_at=now() where id=$1',[id(3)]);
 await login(1);
 await db.query("select review_professor($1,'approved','pro')",[id(3)]);
 await assert.rejects(db.query("select review_professor($1,'rejected','basic')",[id(3)]),/analisada/);
 await login(3);
 await db.query('insert into students values($1,$2,null)',[id(10),id(3)]);
 await db.exec('reset role');
 await db.query('insert into auth.users values($1,$2,$3,now())',[id(4),'student@example.com',JSON.stringify({role:'aluno'})]);
 await login(4);
 await assert.rejects(db.query('insert into students values($1,$2,null)',[id(11),id(4)]));
 await assert.rejects(db.exec('insert into plans values(null)'));
 await db.exec('reset role');
 await db.query('insert into auth.users values($1,$2,$3,now())',[id(5),'rejected@example.com',JSON.stringify({role:'professor'})]);
 await login(1); await db.query("select review_professor($1,'rejected','basic')",[id(5)]);
 await login(5); await assert.rejects(db.exec('insert into exercises values(null)'));
 await db.exec(`reset role; update profiles set active=false where id='${id(1)}'`);
 await login(1); await assert.rejects(db.query("select review_professor($1,'approved','basic')",[id(5)]),/administrador/);
 } finally {await db.close();}
});
